name: CI/CD Base Workflow
on:
  workflow_call:


jobs:
  base-setup:
    name: ğŸ—ºï¸ Base Setup
    runs-on: ubuntu-latest

    steps:
      - name: âœ… Checkout
        uses: actions/checkout@v3
      - name: ğŸŒ Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.2"
